# -*- coding: utf-8 -*-
"""Membuat Model NLP dengan TensorFlow Dicoding

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbvAYeR_Is9XCJb7gebtdVl6ICGIQa4w
"""

#data diri
#Nama: Era Syafina
#dataset : https://www.kaggle.com/datasets/balabaskar/bitcoin-news-articles-text-corpora

import pandas as pd
df = pd.read_csv('/content/bitcoin_articles.csv')

df = df.drop(columns=[
    'author', 'title', 'authors', 'country', 'language', 'excerpt',
    'article_id', 'published_date', 'link', 'clean_url', 'rights',
    'article_rank', 'media', 'twitter_account', 'article_score'
])

df.head()

df.info()

kategory = pd.get_dummies(df.topic)

new_df = pd.concat([df, kategory], axis=1)
new_df = new_df.drop(columns=['topic'])
new_df['summary']= new_df['summary'].fillna('').apply(str)

new_df.head()

df['topic'].value_counts()

summary = new_df['summary'].values
label = new_df[[
    'beauty', 'business', 'economics',
    'energy', 'entertainment',
    'finance', 'food', 'news',
    'politics', 'science', 'sport',
    'tech', 'world'
]].values

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("popular")

index = 0
while index < len(summary):
    tokenizer = nltk.RegexpTokenizer(r"\w+")
    new_words = tokenizer.tokenize(str(summary[index]))
    new_words = " ".join(new_words)

    stop_words = set(stopwords.words('english'))
    tokenizer = nltk.RegexpTokenizer(r"\w+")
    word_tokens = tokenizer.tokenize(new_words)
    filtered_sentence = [w for w in word_tokens if w.lower() not in stop_words]
    summary[index] = " ".join(filtered_sentence)

    index += 1

from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(summary, label, test_size=0.2)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000, oov_token='')
tokenizer.fit_on_texts(data_train)

sekuens_train = tokenizer.texts_to_sequences(data_train)
sekuens_test = tokenizer.texts_to_sequences(data_test)

padded_train = pad_sequences(sekuens_train)
padded_test = pad_sequences(sekuens_test)

import tensorflow as tf

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs = {}):
    if(logs.get('val_accuracy') > 0.81):
      print("\n accuracy model sudah > 81")
      self.model.stop_training = True

callbacks = myCallback()

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000, output_dim=100),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(526, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(13, activation='softmax')
])

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

num_epochs = 50

history = model.fit(
    padded_train, target_train,
    steps_per_epoch = 10,
    epochs=num_epochs,
    validation_data=(padded_test, target_test),
    batch_size=32,
    validation_steps = 10,
    verbose=2,
    callbacks = [callbacks]
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Akurasi Model')
plt.ylabel('accuracy')
plt.xlabel('epochs')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

print('\n')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Loss Model')
plt.ylabel('loss')
plt.xlabel('epochs')
plt.legend(['train', 'test'], loc='lower left')
plt.show()